branches:
  only:
    - main
os: osx
language: node_js
node_js:
- '12.13'

before_install:
- npm i -g npm@6.12.0

install:
- npm install

# deploy:
# - provider: script
#   script: yarn deploy:production
#   skip_cleanup: true
#   on:
#     branch: master
